/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "tc275_oled.h"
#include "tc275_shared_IPC.h"
#include "IfxStm.h"
#include "string.h"
#include "tc275_common_structs.h"
#include "tc275_uart_app.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent cpuSyncEvent = 0;

extern void core1_main(void);
extern void core2_main(void);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
// Initialize shared data not static so other cores can see it
//volatile Shared_Data_t g_SharedData = {0, STATE_WAITING_FOR_CORE1};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/**
 * @brief delayMS
 *
 * @param[in] ms    miliseconds to wait
 *
 * Simple custom blocking custom delay function
 */
void delayMS(uint32 ms){
    uint32 stmFreq = IfxScuCcu_getStmFrequency();
    uint64 ticks = ((uint64)stmFreq * ms) / 1000;
    uint32 startTime = IfxStm_getLower(&MODULE_STM0);
    while((IfxStm_getLower(&MODULE_STM0) - startTime) < ticks);
}

/*********************************************************************************************************************/
/*-------------------------------------------------------Main--------------------------------------------------------*/
/*********************************************************************************************************************/

void core0_main (void)
{
    IfxCpu_enableInterrupts();

    IfxScuWdt_disableCpuWatchdog (IfxScuWdt_getCpuWatchdogPassword ());
    IfxScuWdt_disableSafetyWatchdog (IfxScuWdt_getSafetyWatchdogPassword ());

    // Wake up other cores
    IfxCpu_startCore(&MODULE_CPU1, (uint32)&core1_main);
    IfxCpu_startCore(&MODULE_CPU2, (uint32)&core2_main);

    /* Cpu sync event wait */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    initUART();

    c6dofimu14_axis_t local_buffer;
    char buffer[64];

    while (1)
    {
        // ---------------------------------------------------------------------
        // STEP 1: READ from Core 1 (Producer)
        // ---------------------------------------------------------------------

        // Fix: Cast to (IfxCpu_mutexLock*) to satisfy compiler warning
        while(!IfxCpu_acquireMutex((IfxCpu_mutexLock*)&g_SharedMem_C1_to_C0.mutex));

        local_buffer = g_SharedMem_C1_to_C0.data; // Copy data locally
        IfxCpu_releaseMutex((IfxCpu_mutexLock*)&g_SharedMem_C1_to_C0.mutex);

        // ---------------------------------------------------------------------
        // STEP 2: WRITE to Core 2 (Consumer)
        // ---------------------------------------------------------------------
        snprintf(buffer, sizeof(buffer),
                 "X: %d, Y: %d\n",
                 local_buffer.x, local_buffer.y);
        uart_sendMessage((uint8 * )buffer, strlen(buffer));
        delayMS(20);

        // Forward to Core 2
        // Fix: Cast to (IfxCpu_mutexLock*) for the blocking wait
        while (!IfxCpu_acquireMutex((IfxCpu_mutexLock*)&g_SharedMem_C0_to_C2.mutex));

        g_SharedMem_C0_to_C2.data = local_buffer;
        g_SharedMem_C0_to_C2.update_count++;

        IfxCpu_releaseMutex((IfxCpu_mutexLock*)&g_SharedMem_C0_to_C2.mutex);



        // Run loop at reasonable speed (50Hz)
        delayMS(20);
    }
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
