/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <tc275_shared_IPC.h>
#include <IfxStm.h>
#include "tc275_c6dofimu.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
extern IfxCpu_syncEvent cpuSyncEvent;
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------------Main--------------------------------------------------------*/
/*********************************************************************************************************************/

/**
 * @brief Core 1 main function.
 *
 * Acts as the *producer*.
 * Initializes the 6-DOF IMU and periodically reads the accelerometer axes.
 * Each new sample is written to the shared memory block `g_SharedMem_C1_to_C0` under mutex protection.
 */
void core1_main (void)
{
    IfxCpu_enableInterrupts();
    /*
     * !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
    IfxScuWdt_disableCpuWatchdog (IfxScuWdt_getCpuWatchdogPassword ());

    /* Cpu sync event wait*/
    IfxCpu_waitEvent(&cpuSyncEvent, 1);


    c6dofimu14_init();
    c6dofimu14_axis_t axis = {0,0,0};

    while (1)
    {

        c6dofimu14_read_accel_axis(&axis);


        // 2. WRITE to Shared Memory (C1 -> C0)
        // Try to acquire the lock
        if (IfxCpu_acquireMutex((IfxCpu_mutexLock *)&g_SharedMem_C1_to_C0.mutex))
        {
            // Critical Section
            g_SharedMem_C1_to_C0.data.x = axis.x;
            g_SharedMem_C1_to_C0.data.y = axis.y;
            g_SharedMem_C1_to_C0.update_count++;

            // Release lock
            IfxCpu_releaseMutex((IfxCpu_mutexLock *)&g_SharedMem_C1_to_C0.mutex);
        }

        // Wait a bit (simulate 100Hz sensor rate)
        IfxStm_waitTicks(&MODULE_STM1, IfxStm_getTicksFromMilliseconds(&MODULE_STM1, 10));
    }
}
