/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "tc275_oled.h"
#include "tc275_uart_app.h"
#include "tc275_shared_IPC.h"
#include <stdio.h>

#include "tc275_common_structs.h"

extern IfxCpu_syncEvent cpuSyncEvent;

void core2_main (void)
{
    IfxCpu_enableInterrupts();
    /*
     * !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
    IfxScuWdt_disableCpuWatchdog (IfxScuWdt_getCpuWatchdogPassword ());

    /* Cpu sync event wait*/
    //IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    // Hardware Init
    init_QSPI1_Module();
    init_OLED_GPIO();
    oledc_init();

    oledc_fill_screen(OLEDC_COLOR_BLACK);
    oledc_hud();

    c6dofimu14_axis_t display_data = {0};
    uint32 last_update = 0;


    while (1)
    {
        // 1. READ from Core 0
        if (IfxCpu_acquireMutex(&g_SharedMem_C0_to_C2.mutex))
        {
            // Only update if count changed
            if(g_SharedMem_C0_to_C2.update_count != last_update) {
                display_data = g_SharedMem_C0_to_C2.data;
                last_update = g_SharedMem_C0_to_C2.update_count;
            }
            IfxCpu_releaseMutex(&g_SharedMem_C0_to_C2.mutex);
        }

        // 2. UPDATE SCREEN
        // Clear previous bubble (simple way: redraw center black, or full clear)
        // Ideally, optimize this to only clear old pos. For now, fill black is safe but flickery.
        oledc_fill_screen(OLEDC_COLOR_BLACK);
        oledc_hud();

        // Calculate Position (Map -10..10 tilt to 0..96 pixels)
        // Center is 48.
        int pos_x = 48 + (int)(display_data.x * 4);
        int pos_y = 48 + (int)(display_data.y * 4);

        // Clamp to screen edges
        if(pos_x < 0) pos_x = 0; if(pos_x > 90) pos_x = 90;
        if(pos_y < 0) pos_y = 0; if(pos_y > 90) pos_y = 90;

        // Draw Bubble
        oledc_rectangle(pos_x, pos_y, pos_x+6, pos_y+6, OLEDC_COLOR_RED);

        // Limit Framerate (~20 FPS)
        IfxStm_waitTicks(&MODULE_STM0, IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 50));

    }

}
