/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "tc275_oled.h"
#include "tc275_uart_app.h"
#include "tc275_shared_IPC.h"
#include <stdio.h>
#include "tc275_common_structs.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

extern IfxCpu_syncEvent cpuSyncEvent;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/**
 * @brief delayMS
 *
 * @param[in] data    IMU data
 * @param[in] color   color of the bubble
 *
 * Draw the bubble/rectange with coordinates received from IMU onto OLED C
 */
void draw_bubble(c6dofimu14_axis_t *data, uint16 color){
    // 1. Calculate offset (-3 pixels)
    // IMPORTANT: Cast to 'int' so negative values can be checked.
    int start_x = (int)data->x - 3;
    int start_y = (int)data->y - 3;

    // 2. Safety check (clamping)
    // If the offset results in a negative value, clamp it to 0.
    if (start_x < 0) start_x = 0;
    if (start_y < 0) start_y = 0;

    // Upper/right boundary check
    // Prevent drawing beyond pixel 95.
    if (start_x > 89) start_x = 89; // 95 - 6 Pixel Größe
    if (start_y > 89) start_y = 89;

    // 3. Draw
    // Use start_x/start_y for both start and end (+6) so the box is always 6 px.
    oledc_rectangle((uint8)start_x, (uint8)start_y, (uint8)(start_x+6), (uint8)(start_y+6), color);
}

/*********************************************************************************************************************/
/*-------------------------------------------------------Main--------------------------------------------------------*/
/*********************************************************************************************************************/

/**
 * @brief Core 2 main function.
 *
 * Acts as the *consumer*.
 * Initializes the MikroE OLED C Click display and renders a "bubble" indicator.
 * Reads the latest sample from `g_SharedMem_C0_to_C2` (only when `update_count` changes) and updates the HUD/bubble color accordingly.
 */
void core2_main (void)
{
    IfxCpu_enableInterrupts();
    /*
     * !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
    IfxScuWdt_disableCpuWatchdog (IfxScuWdt_getCpuWatchdogPassword ());

    /* Cpu sync event wait*/
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    
    // Hardware Init
    oledc_init();
    
    oledc_fill_screen(OLEDC_COLOR_BLACK);
    oledc_hud();

    c6dofimu14_axis_t display_data = {0};
    uint32 last_update = 0;

    while (1)
    {
        // clear previous frame
        draw_bubble(&display_data, OLEDC_COLOR_BLACK);

        //Read from Core 0
        if (IfxCpu_acquireMutex((IfxCpu_mutexLock *)&g_SharedMem_C0_to_C2.mutex))
        {
            // Only update if count changed
            if(g_SharedMem_C0_to_C2.update_count != last_update) {
                display_data = g_SharedMem_C0_to_C2.data;
                last_update = g_SharedMem_C0_to_C2.update_count;
            }
            IfxCpu_releaseMutex((IfxCpu_mutexLock *)&g_SharedMem_C0_to_C2.mutex);
        }

        //Update Screen
        oledc_hud();

        //Draw Bubble
        if(display_data.x > 43 && display_data.x < 53
                && display_data.y > 43 && display_data.y < 53){
            draw_bubble(&display_data, OLEDC_COLOR_GREEN);
        }
        else{
            draw_bubble(&display_data, OLEDC_COLOR_RED);
        }

        IfxStm_waitTicks(&MODULE_STM0, IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 10));
    }
}
