/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "tc275_oled.h"
#include "tc275_uart_app.h"
#include "tc275_shared_IPC.h"
#include <stdio.h>

#include "tc275_common_structs.h"

extern IfxCpu_syncEvent cpuSyncEvent;

void draw_rectangle(c6dofimu14_axis_t *data, uint16 color){
    oledc_rectangle(data->x, data->y, data->x+6, data->y+6, color);
}

void core2_main (void)
{
    IfxCpu_enableInterrupts();
    /*
     * !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog in the demo if it is required and also service the watchdog periodically
     * */
    IfxScuWdt_disableCpuWatchdog (IfxScuWdt_getCpuWatchdogPassword ());

    /* Cpu sync event wait*/
    //IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    // Hardware Init
    init_QSPI1_Module();
    init_OLED_GPIO();
    oledc_init();

    oledc_fill_screen(OLEDC_COLOR_BLACK);
    oledc_hud();

    c6dofimu14_axis_t display_data = {0};
    uint32 last_update = 0;

    int rec_w = 6;
    int rec_h = 6;

    while (1)
    {
        draw_rectangle(&display_data, OLEDC_COLOR_BLACK);

        // 1. READ from Core 0
        if (IfxCpu_acquireMutex(&g_SharedMem_C0_to_C2.mutex))
        {
            // Only update if count changed
            if(g_SharedMem_C0_to_C2.update_count != last_update) {
                display_data = g_SharedMem_C0_to_C2.data;
                last_update = g_SharedMem_C0_to_C2.update_count;
            }
            IfxCpu_releaseMutex(&g_SharedMem_C0_to_C2.mutex);
        }

        // 2. UPDATE SCREEN

        oledc_hud();

        // TODO: Calculate Position

        // Draw Bubble
        draw_rectangle(&display_data, OLEDC_COLOR_RED);

        IfxStm_waitTicks(&MODULE_STM0, IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 10));
    }

}
