/**********************************************************************************************************************
 * \file tc275_oled.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "tc275_oled.h"
#include "IfxQspi_SpiMaster.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define IFX_INTPRIO_QSPI1_TX  10
#define IFX_INTPRIO_QSPI1_RX  11
#define IFX_INTPRIO_QSPI1_ER  12

#define OLED_RST  &MODULE_P10, 4
#define OLED_DC   &MODULE_P13, 2

const uint8  _OLEDC_FO_HORIZONTAL       = 0x00;
const uint8   _OLEDC_FO_VERTICAL         = 0x01;
const uint8   _OLEDC_FO_VERTICAL_COLUMN  = 0x02;

/*
*********************************************************************************************************
*                                             REMAMP
*********************************************************************************************************
*/
#define _OLEDC_RMP_INC_HOR         0x00
#define _OLEDC_RMP_INC_VER         0x01
#define _OLEDC_RMP_COLOR_NOR       0x00
#define _OLEDC_RMP_COLOR_REV       0x02
#define _OLEDC_RMP_SEQ_RGB         0x00
#define _OLEDC_RMP_SEQ_BGR         0x04
#define _OLEDC_RMP_SCAN_NOR        0x00
#define _OLEDC_RMP_SCAN_REV        0x10
#define _OLEDC_RMP_SPLIT_DISABLE   0x00
#define _OLEDC_RMP_SPLIT_ENABLE    0x20
#define _OLEDC_COLOR_65K           0x00
#define _OLEDC_COLOR_262K          0x80
#define _OLEDC_IMG_HEAD            0x06


/*
*********************************************************************************************************
*                                             OLED SETTINGS
*********************************************************************************************************
*/
const uint8  _OLEDC_SCREEN_WIDTH    = 0x60;
const uint8  _OLEDC_SCREEN_HEIGHT   = 0x60;
const uint8 _OLEDC_SCREEN_SIZE     = 0x2400;

#define  _OLEDC_ROW_OFF          0x00
#define  _OLEDC_COL_OFF          0x10

/*
*********************************************************************************************************
*                                             COMMANDS
*********************************************************************************************************
*/
const uint8  _OLEDC_SET_COL_ADDRESS   = 0x15;
const uint8  _OLEDC_SET_ROW_ADDRESS   = 0x75;
const uint8  _OLEDC_WRITE_RAM         = 0x5C;
const uint8  _OLEDC_READ_RAM          = 0x5D;
const uint8  _OLEDC_SET_REMAP         = 0xA0;
const uint8  _OLEDC_SET_START_LINE    = 0xA1;
const uint8  _OLEDC_SET_OFFSET        = 0xA2;
const uint8  _OLEDC_MODE_OFF          = 0xA4;
const uint8  _OLEDC_MODE_ON           = 0xA5;
const uint8  _OLEDC_MODE_NORMAL       = 0xA6;
const uint8  _OLEDC_MODE_INVERSE      = 0xA7;
const uint8  _OLEDC_FUNCTION          = 0xAB;
const uint8  _OLEDC_SLEEP_ON          = 0xAE;
const uint8  _OLEDC_SLEEP_OFF         = 0xAF;
const uint8  _OLEDC_NOP              = 0xB0;
const uint8  _OLEDC_SET_RESET_PRECH  = 0xB1;
const uint8  _OLEDC_ENHANCEMENT      = 0xB2;
const uint8  _OLEDC_CLOCK_DIV         = 0xB3;
const uint8  _OLEDC_VSL               = 0xB4;
const uint8  _OLEDC_GPIO              = 0xB5;
const uint8  _OLEDC_SETSEC_PRECH      = 0xB6;
const uint8  _OLEDC_GREY_SCALE        = 0xB8;
const uint8  _OLEDC_LUT               = 0xB9;
const uint8  _OLEDC_PRECH_VOL         = 0xBB;
const uint8  _OLEDC_VCOMH             = 0xBE;
const uint8  _OLEDC_CONTRAST          = 0xC1;
const uint8  _OLEDC_MASTER_CONTRAST   = 0xC7;
const uint8  _OLEDC_MUX_RATIO         = 0xCA;
const uint8  _OLEDC_COMMAND_LOCK      = 0xFD;
const uint8  _OLEDC_SCROLL_HOR        = 0x96;
const uint8  _OLEDC_START_MOV         = 0x9E;
const uint8  _OLEDC_STOP_MOV          = 0x9F;

static uint8 _OLEDC_DEFAULT_MUX_RATIO      = 95;
static uint8 _OLEDC_DEFAULT_START_LINE     = 0x80;
static uint8 _OLEDC_DEFAULT_OFFSET         = 0x20;

static uint8 _OLEDC_DEFAULT_OLED_LOCK      = 0x12;
static uint8 _OLEDC_DEFAULT_CMD_LOCK       = 0xB1;
static uint8 _OLEDC_DEFAULT_DIVSET         = 0xF1;
static uint8 _OLEDC_DEFAULT_PRECHARGE      = 0x32;
static uint8 _OLEDC_DEFAULT_VCOMH          = 0x05;
static uint8 _OLEDC_DEFAULT_MASTER_CONT    = 0xCF;
static uint8 _OLEDC_DEFAULT_PRECHARGE_2    = 0x01;

static uint8 cols[ 2 ]    = { _OLEDC_COL_OFF, _OLEDC_COL_OFF + 95 };
static uint8 rows[ 2 ]    = { _OLEDC_ROW_OFF, _OLEDC_ROW_OFF + 95 };

static uint8 _OLEDC_DEFAULT_REMAP = _OLEDC_RMP_INC_HOR | _OLEDC_RMP_COLOR_REV |
                                _OLEDC_RMP_SEQ_RGB | _OLEDC_RMP_SCAN_REV |
                                _OLEDC_RMP_SPLIT_ENABLE | _OLEDC_COLOR_65K;

static  uint8 _OLEDC_DEFAULT_VSL[ 3 ]       = { 0xA0, 0xB5, 0x55 };
static  uint8 _OLEDC_DEFAULT_CONTRAST[ 3 ]  = { 0x8A, 0x51, 0x8A };

static const uint8*   _font;
static uint16         _font_color;
static uint16          _font_orientation;
static uint16         _font_first_char;
static uint16         _font_last_char;
static uint16         _font_height;
//static uint16         x_cord;
//static uint16         y_cord;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxQspi_SpiMaster g_qspi2_handle; // Global handle for the module
static IfxQspi_SpiMaster g_qspi;
static IfxQspi_SpiMaster_Channel g_qspiChannel;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(qspi1TxISR, 0, IFX_INTPRIO_QSPI1_TX) { IfxQspi_SpiMaster_isrTransmit(&g_qspi); }
IFX_INTERRUPT(qspi1RxISR, 0, IFX_INTPRIO_QSPI1_RX) { IfxQspi_SpiMaster_isrReceive(&g_qspi); }
IFX_INTERRUPT(qspi1ErISR, 0, IFX_INTPRIO_QSPI1_ER) { IfxQspi_SpiMaster_isrError(&g_qspi); }


void init_QSPI1_Module(void) {
    IfxQspi_SpiMaster_Config spiMasterConfig;
    // Initialize default values
    IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, &MODULE_QSPI1);

    // --- 1. Module Configuration (No .base) ---
    spiMasterConfig.mode             = IfxQspi_Mode_master;
    spiMasterConfig.maximumBaudrate  = 10000000; // 10 MHz
    spiMasterConfig.txPriority       = IFX_INTPRIO_QSPI1_TX;
    spiMasterConfig.rxPriority       = IFX_INTPRIO_QSPI1_RX;
    spiMasterConfig.erPriority       = IFX_INTPRIO_QSPI1_ER;
    spiMasterConfig.isrProvider      = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    // --- 2. Pin Configuration (Using Designated Initializers) ---
    // This format prevents "incompatible pointer" errors by explicitly naming fields
    const IfxQspi_SpiMaster_Pins pins = {
        .sclk       = &IfxQspi1_SCLK_P10_2_OUT,
        .sclkMode   = IfxPort_OutputMode_pushPull,

        .mtsr       = &IfxQspi1_MTSR_P10_3_OUT,
        .mtsrMode   = IfxPort_OutputMode_pushPull,

        .mrst       = &IfxQspi1_MRSTA_P10_1_IN,
        .mrstMode   = IfxPort_InputMode_pullUp,

        .pinDriver  = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    spiMasterConfig.pins = &pins;

    // Initialize the Module
    IfxQspi_SpiMaster_initModule(&g_qspi, &spiMasterConfig);

    // --- 3. Channel Configuration ---
    IfxQspi_SpiMaster_ChannelConfig channelConfig;
    IfxQspi_SpiMaster_initChannelConfig(&channelConfig, &g_qspi);

    // Baudrate is inside the ".ch" structure in your library version
    channelConfig.ch.baudrate = 5000000; // 5 MHz

    // Chip Select Configuration (P10.5)
    channelConfig.sls.output.pin    = &IfxQspi1_SLSO9_P10_5_OUT;
    channelConfig.sls.output.mode   = IfxPort_OutputMode_pushPull;
    channelConfig.sls.output.driver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    // Protocol Settings (inside .ch.mode)
    channelConfig.ch.mode.clockPolarity = IfxQspi_ClockPolarity_idleLow;
    channelConfig.ch.mode.shiftClock    = IfxQspi_ShiftClock_shiftTransmitDataOnTrailingEdge;
    channelConfig.ch.mode.dataHeading   = IfxQspi_DataHeading_msbFirst;

    // Initialize the Channel
    IfxQspi_SpiMaster_initChannel(&g_qspiChannel, &channelConfig);
}


void init_OLED_GPIO(void) {
    // Set pins as Output Push-Pull
    IfxPort_setPinModeOutput(OLED_RST, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(OLED_DC,  IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);

    // Initial state: Keep Reset HIGH
    IfxPort_setPinHigh(OLED_RST);
}


void oled_sendCommand(uint8 command) {
    IfxPort_setPinLow(OLED_DC);  // Command mode
    IfxQspi_SpiMaster_exchange(&g_qspiChannel, &command, NULL_PTR, 1);
    while (IfxQspi_SpiMaster_getStatus(&g_qspiChannel) == IfxQspi_Status_busy);
}


//void oledc_command(CPU_INT08U command, CPU_INT08U *args, CPU_INT16U args_len){
//    CPU_INT08U *ptr = args;
//
//    hal_gpio_csSet(LOW);
//    hal_gpio_dcSet(LOW);
//
//    hal_spiWrite(&command, 1);
//
//    hal_gpio_dcSet(HIGH);
//
//    if(args_len){
//        hal_spiWrite(ptr, args_len);
//    }
//
//    hal_gpio_csSet(HIGH);
//}

void oled_sendData(uint8 data) {
    IfxPort_setPinHigh(OLED_DC); // Data mode
    IfxQspi_SpiMaster_exchange(&g_qspiChannel, &data, NULL_PTR, 1);
    while (IfxQspi_SpiMaster_getStatus(&g_qspiChannel) == IfxQspi_Status_busy);
}

void oled_init(void) {
    // Hardware Reset
    IfxPort_setPinLow(OLED_RST);
    // wait ~10ms
    IfxPort_setPinHigh(OLED_RST);

    // Initialization Sequence
    oled_sendCommand(0xAE); // Display OFF
    oled_sendCommand(0xD5); // Set Display Clock Divide Ratio
    oled_sendCommand(0x80); // Suggested ratio
    oled_sendCommand(0xA8); // Set Multiplex Ratio
    oled_sendCommand(0x3F); // 1/64 duty
    oled_sendCommand(0x8D); // Charge Pump
    oled_sendCommand(0x14); // Enable charge pump
    oled_sendCommand(0xAF); // Display ON
}

// Defines for Screen Size (Adjust if your Mikroe board is 96x39)
#define OLED_WIDTH   96   // Standard Mikroe OLED Click width
#define OLED_HEIGHT  96   // Standard Mikroe OLED Click height


void oled_fillScreen(uint8 pattern) {
    // 1. Set Memory Addressing Mode to Horizontal (0x00)
    oled_sendCommand(0x20);
    oled_sendCommand(0x00);

    // 2. Set Column Address (Start at 0, End at 127)
    // Even if screen is 96px, the controller supports 128 columns.
    // It is safer to clear the whole buffer.
    oled_sendCommand(0x21);
    oled_sendCommand(0x00);
    oled_sendCommand(0x7F); // 127

    // 3. Set Page Address (Start at 0, End at 7)
    oled_sendCommand(0x22);
    oled_sendCommand(0x00);
    oled_sendCommand(0x07);

    // 4. Send Data Stream
    // Total bytes = 128 columns * 8 pages = 1024 bytes
    // We fill the entire controller RAM to be sure.
    uint16 i;
    for(i = 0; i < 1024; i++) {
        oled_sendData(pattern);
    }
}
