/**********************************************************************************************************************
 * \file tc275_oled.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef TC275_OLED_H_
#define TC275_OLED_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
// --- Colors (RGB565) ---
#define OLEDC_COLOR_BLACK   0x0000
#define OLEDC_COLOR_WHITE   0xFFFF
#define OLEDC_COLOR_RED     0xF800
#define OLEDC_COLOR_GREEN   0x07E0
#define OLEDC_COLOR_BLUE    0x001F
#define OLEDC_COLOR_CYAN    0x07FF
#define OLEDC_COLOR_MAGENTA 0xF81F
#define OLEDC_COLOR_YELLOW  0xFFE0

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/**
 * @brief OLED C init
 *
 * OLED C command init sequence
 */
void oledc_init(void);

/*
*********************************************************************************************************
*                                             Drawing Functions
*********************************************************************************************************
*/

/**
 * @brief OLED C fill screen
 *
 * @param[in] color     color choice
 *
 * Fill screen with specified color
 */
void oledc_fill_screen(uint16 color);

/**
 * @brief OLED C rectangle
 *
 * @param[in] start_col     start column coordinate
 * @param[in] start_row     start row coordinate
 * @param[in] end_col       end column cordinate
 * @param[in] end_row       end row coordinate
 * @param[in] color         color of rectangle
 *
 * Draw a filled rectangle from start coordiantes to end coordinates
 */
void oledc_rectangle(uint8 start_col, uint8 start_row, uint8 end_col, uint8 end_row, uint16 color);

/**
 * @brief OLED C line
 *
 * @param[in] start_col     start column coordinate
 * @param[in] start_row     start row coordinate
 * @param[in] end_col       end column cordinate
 * @param[in] end_row       end row coordinate
 * @param[in] color         color of line
 *
 * Draw a line from specified coordinates to other coordinates with specified color
 */
void oledc_line(uint8 x1, uint8 y1, uint8 x2, uint8 y2, uint16 color);

/**
 * @brief OLED C hud
 *
 * Draw green crosshair
 */
void oledc_hud(void); // Draws the crosshair

#endif /* TC275_OLED_H_ */
